version: "3.9"


x-vllm-common:
  &common
  image: vllm/vllm-openai:latest
  restart: unless-stopped
  environment:
    TZ: "Asia/Shanghai"
  volumes:
    - /data/models:/models # Please modify this to the actual model directory.
  networks:
    - vllm


services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx configuration file.
    networks:
      - vllm
    depends_on:
      - chat_generate
      - embed
      - reranker


  chat_generate:
    <<: *common
    shm_size: '10.24gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
      # Modify the `model` parameter to the path where you have downloaded the model, and adjust `tensor-parallel-size` according to the number of GPUs you intend to use.
    command: [ "--model","/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",  "--enable-prefix-caching", "--host", "0.0.0.0", "--port", "8000", "--served-model-name", "gpt-4", "--distributed-executor-backend","ray","--tensor-parallel-size","2","--pipeline-parallel-size", "1","--enable-reasoning","--reasoning-parser","deepseek_r1"]

  embed:
    <<: *common
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: ['3']
    command: [ "--model","/models/maple77/gte-large-zh",  "--host", "0.0.0.0", "--port", "8000", "--task", "embed", "--served-model-name", "gte-large-zh"]

  reranker:
    <<: *common
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: ['3']
    command: >
      --model /models/Qwen3-Reranker-0.6
      --host 0.0.0.0
      --port 8005
      --gpu-memory-utilization 0.2
      --max-model-len 2048
      --runner pooling
      --hf_overrides '{"architectures": ["Qwen3ForSequenceClassification"],"classifier_from_token": ["no", "yes"],"is_original_qwen3_reranker": true}'
      --chat-template examples/pooling/score/template/qwen3_reranker.jinja


networks:
  vllm:
