events {}
http {
    server {
        listen 80;

        # Chat服务代理
        location /v1/chat/completions {
             proxy_pass http://chat_generate:8000/v1/chat/completions;
             proxy_set_header Host $host;
         }

        # Embedding服务代理
        location /v1/embeddings {
            proxy_pass http://embed:8000/v1/embeddings;
            proxy_set_header Host $host;
        }

        # Reranker服务代理
        location /rerank {
            proxy_pass http://reranker:8000/rerank;
            proxy_set_header Host $host;
        }

        # Reranker服务代理 Jina AI
        location /v1/rerank {
            proxy_pass http://reranker:8000/v1/rerank;
            proxy_set_header Host $host;
        }

        # Reranker服务代理 Cohere
        location /v2/rerank {
            proxy_pass http://reranker:8000/v2/rerank;
            proxy_set_header Host $host;
        }

        # 添加默认路由规则
        location / {
            proxy_pass http://chat_generate:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}